### ISSUE TITLE
Config for ImageOptimize Plugin

### ISSUE THREAD

**Issue by vaughn-taylor** [CreateSean/craft-starter#2]
In case anyone is using the ImageOptimize plugin from NYStudio107, you'll need to add several packages on line 130 of .ddev/config.yaml:

`webimage_extra_packages: [jpegoptim optipng gifsicle webp]`

You'll also need the NPM package "svgo". This can be installed by creating a Dockerfile in .ddev/web-build/Dockerfile (there should be a Dockerfile.example file already there - just remove the '.example'). Your final Dockerfile should look like this:

`ARG BASE_IMAGE`
`FROM $BASE_IMAGE`
`RUN sudo npm install -g svgo`

This will satisfy the needs of ImageOptimize:

<img width="1311" alt="Screen Shot 2022-01-26 at 1 06 11 PM" src="https://user-images.githubusercontent.com/2078376/151229822-c7faf77d-3f23-4cd6-88e5-e8339b2a7a0e.png">

**Comment by CreateSean** [comment]
@vaughn-taylor Thanks for this - will include a link to this in the readme file for anyone using the Image Optimize plugin

Noticed one type - the changes should be made in line 130 of `.ddev/config.yaml` not project.yaml

**Comment by vaughn-taylor** [comment]
@CreateSean good catch! You are correct sir. Sorry, I was thinking of CraftCMS's config.

**Comment by dualhub** [comment]
This is fantastic @vaughn-taylor! Thanks for showing me the way.
