### ISSUE TITLE
Fatal Error, Undefined Constant...

### ISSUE THREAD

**Issue by kerns** [CreateSean/craft-starter#3]
<img width="1366" alt="Screenshot 2022-03-08 at 13 28 00" src="https://user-images.githubusercontent.com/20254/157238306-3ba48a5d-c234-4fcf-8d95-f306edb06a4b.png">

Not sure what the issue is but thought I should report it.

**Comment by CreateSean** [comment]
@kerns Thanks - I didn't see this until just now. Sorry for the late response.

I did a test install with the composer create command `composer create-project createsean/craft-starter .` and it worked for me - this is the latest version using Craft 4.0.3

Have you had any other issues?
