### ISSUE TITLE
Error when running 'npm run export-tw-config'

### ISSUE THREAD

**Issue by migmake** [CreateSean/craft-starter#4]
The command `npm run tw-config-viewer` is working perfectly but the command `npm run export-tw-config` is having an error:
```
npm ERR! Missing script: "export-tw-config"

npm ERR! Did you mean one of these?
npm ERR!     npm run export-tw-viewer # run the "export-tw-viewer" package script
npm ERR!     npm run export-tailwind-config # run the "export-tailwind-config" package script
```
Can you confirm?

**Comment by CreateSean** [comment]
@migswd I ran the `npm run tw-config-viewer` commands just now and it worked for me.

If it's still not working for you try deleting your node_modules folder and running `npm install` again.
